# Generated by Django 2.1.2 on 2018-11-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('ONE', 'I'), ('TWO', 'II'), ('THREE', 'III'), ('FOUR', 'IV'), ('FIVE', 'V'), ('SIX', 'VI'), ('SEVEN', 'VII'), ('EIGHT', 'VIII')], default='ONE', max_length=100)),
                ('course_name', models.CharField(choices=[('Introduction To Programming', 'Introduction To Programming'), ('Intro To Information Technology', 'Intro To Information Technology'), ('Information Society', 'Information Society'), ('Database Management System', 'Database Management System'), ('Operating System', 'Operating System'), ('Computer Networks', 'Computer Networks'), ('Software Engineering', 'Software Engineering'), ('Web Technology', 'Web Technology')], default='Introduction To Programming', max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.CharField(choices=[('Dr Naveen Kumar', 'Dr Naveen Kumar'), ('Dr Manik Lal Das', 'Dr Manik Lal Das'), ('Dr P M Jat', 'Dr P M Jat'), ('Dr Ashish Phophalia', 'Dr Ashish Phophalia'), ('Dr Asim Banerjee', 'Dr Asim Banerjee'), ('Mr Santosh Bharti', 'Mr Santosh Bharti')], default='', max_length=100)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='Mentor', max_length=100)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
