# Generated by Django 2.0.5 on 2018-10-07 07:53

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181006_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('ONE', 'I'), ('TWO', 'II'), ('THREE', 'III'), ('FOUR', 'IV'), ('FIVE', 'V'), ('SIX', 'VI'), ('SEVEN', 'VII'), ('EIGHT', 'VIII')], default='ONE', max_length=100),
        ),
    ]
