# Generated by Django 2.0.5 on 2018-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181007_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('ONE', 'I'), ('TWO', 'II'), ('THREE', 'III'), ('FOUR', 'IV'), ('FIVE', 'V'), ('SIX', 'VI'), ('SEVEN', 'VII'), ('EIGHT', 'VIII')], max_length=100),
        ),
    ]
