# Generated by Django 2.0.5 on 2018-10-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181007_1001'),
        ('App', '0003_auto_20181007_1521'),
    ]

    operations = [
    ]
