# Generated by Django 2.0.5 on 2018-10-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181022_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('ONE', 'I'), ('TWO', 'II'), ('THREE', 'III'), ('FOUR', 'IV'), ('FIVE', 'V'), ('SIX', 'VI'), ('SEVEN', 'VII'), ('EIGHT', 'VIII')], default='ONE', max_length=100),
        ),
    ]
