# Generated by Django 2.0.5 on 2018-10-07 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_merge_20181007_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
