# Generated by Django 2.1.2 on 2018-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20181022_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course_name',
            field=models.CharField(choices=[('Introduction To Programming', 'Introduction To Programming'), ('Intro To Information Technology', 'Intro To Information Technology'), ('Information Society', 'Information Society'), ('Database Management System', 'Database Management System'), ('Operating System', 'Operating System'), ('Computer Networks', 'Computer Networks'), ('Software Engineering', 'Software Engineering'), ('Web Technology', 'Web Technology')], default='Introduction To Programming', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculty',
            field=models.CharField(choices=[('Dr Naveen Kumar', 'Dr Naveen Kumar'), ('Dr Manik Lal Das', 'Dr Manik Lal Das'), ('Dr P M Jat', 'Dr P M Jat'), ('Dr Ashish Phophalia', 'Dr Ashish Phophalia'), ('Dr Asim Banerjee', 'Dr Asim Banerjee'), ('Mr Santosh Bharti', 'Mr Santosh Bharti')], default='', max_length=100),
        ),
    ]
